name: adversarial-gpu-classification
channels:
  - defaults
dependencies:
  - python=3.8.0
  - pip
  - pillow=8.3.1
  - cudatoolkit
  - cudnn
  - tensorflow-gpu==2.4.1
  - keras==2.4.3
  - pip:
    - h5py==2.10.0
    - opencv-python==4.5.3.56
    - scipy==1.4.1
    - numpy
    - tensorboard
    - tqdm
    - requests
    - matplotlib
    - fiftyone
    - google-cloud-vision
